import = ["/home/traap/.config/alacritty/fonts.toml", "/home/traap/.config/alacritty/themes/.default.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"
WINT_X11_SCALE_FACTOR = "1.0"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/bash"

[window]
opacity = 0.6

[window.class]
general = "Alacritty"
instance = "Alacritty"

# [window.plladding]
# x = 0
# y = 0
