#!/bin/bash
NEWBAR=$1

rm -rv ~/.config/waybar/active/*
cp -rv ~/.config/waybar/${NEWBAR}/* ~/.config/waybar/active

# kill first
[[ $(pidof waybar) ]] && killall -q waybar

# Wait for waybar to exit.
while pgrep -u $UID -x waybar > /dev/null;do sleep 1;done

# start up again
CONFIG="$HOME/.config/waybar/active/config.jsonc"
 STYLE="$HOME/.config/waybar/active/style.css"

if [[ ! $(pidof waybar) ]]; then
	waybar \
    --bar main-bar \
    --log-level error \
    --config ${CONFIG} \
    --style ${STYLE} &
fi
