#!bin/bash
# {{{ Stooges: Honoring Larry, Moe, and Curley ... Nyuk, nyuk, nyuk.
#
# Bash scripting cheatsheet => https://devhints.io/bash

echo ${HOSTNAME} "on" ${OSTYPE}

# -------------------------------------------------------------------------- }}}
# {{{ Disable # Disable ctrl-s and ctrl-q

stty -ixon

# -------------------------------------------------------------------------- }}}
# {{{ Infanite history

HISTSIZE= HISTFILESIZE=

# -------------------------------------------------------------------------- }}}
# {{{ ArchLinux specific keyboard setting.

# Turn off numlock and swap Cap Lock && Escape keys on Arch Linux

if [[ $(uname -r) =~ 'arch' || $(uname -r) =~ 'lts' ]]; then
   numlockx off
   if [[ $(xrandr | rg eDP1 -c) == 1 ]]; then
     setxkbmap -option caps:swapescape
  fi
fi

# -------------------------------------------------------------------------- }}}
# {{{ Customize my bash experience.

# Define functions and paths for this shell.
dotfiles=${HOME}/git/dotfiles

# Customize my shell.
my_array=("functions" "exports" "aliases" "paths" "completions" "prompt" )
for m in ${my_array[@]}; do
  x=$dotfiles/my_$m
  source $x
done

# -------------------------------------------------------------------------- }}}
