#!bin/bash
# {{{ Stooges: Honoring Larry, Moe, and Curly ... Nyuk, nyuk, nyuk.
#
# Bash scripting cheatsheet => https://devhints.io/bash

echo ${HOSTNAME} "running" ${OSTYPE}

# -------------------------------------------------------------------------- }}}
# {{{ Top level exports I used throughout all my scripts.

BBHOME=${HOME}/bb
export BBHOME

if [[ -f ${HOME}/git/dotfiles/bashrc-personal ]]; then
  DOTFILESHOME=${HOME}/git/dotfiles
  export DOTFILESHOME
elif [[ -f ${HOME}/.config/dotfiles/bashrc-personal ]]; then
  DOTFILESHOME=${HOME}/.config/dotfiles
  export DOTFILESHOME
fi

GITHOME=${HOME}/git
export GITHOME

GITPATH=${GITHOME}
export GITPATH

SOUPHOME=${HOME}/soup
export=SOUPHOME

# -------------------------------------------------------------------------- }}}
# {{{ Disable ctrl-s and ctrl-q

stty -ixon

# -------------------------------------------------------------------------- }}}
# {{{ Infanite history

HISTSIZE= HISTFILESIZE=

# -------------------------------------------------------------------------- }}}
# {{{ Customize my bash experience.

# Customize my shell.
my_array=("functions" "exports" "aliases" "paths" "completions" "prompt" )
for m in ${my_array[@]}; do
  x=${DOTFILESHOME}/my_$m
  source $x
done

# Load my keys.
sshkeys

# -------------------------------------------------------------------------- }}}
