#!/bin/bash
# {{{ Operating system specific settings.

if osType "darwin"; then
  alias la='ls -A'
  alias ll='ls -lahG'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Vim keybindings.

set -o vi

# -------------------------------------------------------------------------- }}}
# {{{ latexrun is defined when present.

if fileExists ${HOME}/git/latexrun/latexrun; then
  alias latexrun='${HOME}/git/latexrun/latexrun'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Tmux setup.

if fileExists /usr/bin/tmux; then
  alias tmux='tmux -2'
fi

# -------------------------------------------------------------------------- }}}
# {{{ List

[   -f /usr/bin/bat ] && alias 'cat=bat -p'
[   -f /usr/bin/exa ] && alias ls='exa'
[ ! -f /usr/bin/exa ] && alias ls='ls --color=auto'

# -------------------------------------------------------------------------- }}}
# {{{ General purpose aliases.

alias cls='clear'
alias encrypt='${HOME}/git/dotfiles/encrypt'
alias fde='fd --extension'
alias fgrep='fgrep --color=auto'
alias ga='git add'
alias gc='git commit -m'
alias gbp='gits bb pull'
alias ggp='gits git pull'
alias gl7='git logg -7'
alias glgg='git logg'
alias glg='git log'
alias glgi='git logi'
alias gitv='gits vim'
alias gp='git push'
alias gpp='git pull'
alias grep='grep --color=auto'
alias grh='git reset HEAD'
alias gs='clear && git status'
alias gsuo='git push --set-upstream origin'
alias h='history'
alias kax='sudo killall Xorg'
alias l1='ls -1'
alias lad='ls -lad .*'
alias las='find . -maxdepth 1 -type l -printf "%p -> %l\n" | sort'
alias lass='find . -type l -printf "%p -> %l\n" | sort'
alias me='clear && exec bash'
alias mv='mv -v'
alias n='nvim'
alias np='nvim +PackerSync'
alias nano='vim'
alias pacmann='sudo pacman --noconfirm -S'
alias rbn='sudo reboot now'
alias sa='source ${HOME}/git/dotfiles/my_aliases'
alias sdn='sudo shutdown now'
alias se='source ${HOME}/git/dotfiles/my_exports'
alias sf='source ${HOME}/git/dotfiles/my_functions'
alias sp='source ${HOME}/git/dotfiles/my_paths'
alias ssh='ssh -A'
alias s='source'
alias ta='tmux attach'
alias yayn='yay --noconfirm -S'
alias xz='vi -c "let g:tty='\''$(tty)'\''"'

# -------------------------------------------------------------------------- }}}
# {{{ Aliases to folders within my Git root.

alias ac='cd ${HOME}/git/AllanConsulting'
alias bb='cd ${HOME}/bb'
alias bootd='cd ${HOME}/git/bootstrap'
alias color='cd ${HOME}/git/color'
alias dotb='cd ${HOME}/git/dotfiles/bin'
alias Dc='cd ${HOME}/Documents'
alias Dd='cd ${HOME}/Downloads'
alias fk='cd ${HOME}/git/fk/'
alias gd='cd ${HOME}/git'
alias hh='cd ${HOME}/git/HowardHouse'
alias lspd='cd ${HOME}/.local/share/nvim/lsp_servers'
alias nd='cd ${HOME}/git/nvim'
alias nvimd='cd ${HOME}/git/nvim'
alias packd='cd ${HOME}/.local/share/nvim/site/pack/packer/start'
alias resume='cd ${HOME}/git/resume'
alias sshd='cd ${HOME}/git/ssh'
alias tmuxd='cd ${HOME}/git/tmux'
alias vimd='cd ${HOME}/git/vim'
alias wd='cd ${HOME}/git/wiki'

# -------------------------------------------------------------------------- }}}
# {{{ Brew wants me to own usr/local

if osType "darwin"; then
  alias ulo='sudo chown -R $(whoami) /usr/local'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Repeat command are used when I enable my resume editor.

alias rgl='repeat git logg -6'
alias rgs='repeat git status --short'

# -------------------------------------------------------------------------- }}}
# {{{ Perforce defaults.

if osType "linux"; then
  if hostName "Ryder"; then
    alias p4='${P4DISK}/2013.1/p4'
    alias p4d='${P4DISK}/2013.1/p4d'
  fi
fi

# -------------------------------------------------------------------------- }}}
# {{{ File I edit frequently.

alias ,eb='${EDITOR} ${HOME}/git/dotfiles/bootstrap.vim'
alias ,ec='${EDITOR} ${HOME}/git/ssh/config.vim'
alias ,ed='${EDITOR} ${HOME}/git/vim/custom-dictionary.utf-8.add'
alias ,eg='${EDITOR} ${HOME}/git/ssh/gitconfig'
alias ,en='${EDITOR} ${HOME}/git/vim/nvim.vim'
alias ,ep='${EDITOR} ${HOME}/git/vim/plug.vim'
alias ,em='${EDITOR} ${HOME}/git/vim/minimal-plug.vim'
alias ,et='${EDITOR} ${HOME}/git/tmux/tmux.conf'
alias ,ev='${EDITOR} ${HOME}/git/vim/vimrc'

alias ,ma='${EDITOR} ${HOME}/git/dotfiles/my_aliases'
alias ,mb='${EDITOR} ${HOME}/git/dotfiles/bashrc'
alias ,mc='${EDITOR} ${HOME}/git/dotfiles/my_completions'
alias ,me='${EDITOR} ${HOME}/git/dotfiles/my_exports'
alias ,mf='${EDITOR} ${HOME}/git/dotfiles/my_functions'
alias ,mp='${EDITOR} ${HOME}/git/dotfiles/my_paths'
alias ,mt='${EDITOR} ${HOME}/git/dotfiles/my_prompt'
alias ,mz='${EDITOR} ${HOME}/git/dotfiles/bashrc-personal'

alias ,xb='${EDITOR} ${HOME}/git/dotfiles/bspwmrc'
alias ,xs='${EDITOR} ${HOME}/git/dotfiles/sxhkdrc'

# -------------------------------------------------------------------------- }}}
# {{{ tmux sessions I frequently use.

alias tao='ao ao'
alias tbash='ao bash'
alias tkjv='ao kjv'
alias tnvim='ao nvim'
alias tsoup='ao soup'
alias tssh='ao ssh'
alias tvim='ao vim'
alias twiki='ao wiki'

alias kao='tmux kill-session -t ao'
alias kbash='tmux kill-session -t bash'
alias kkjv='tmux kill-session -t kjv'
alias knvim='tmux kill-session -t nvim'
alias ksoup='tmux kill-session -t soup'
alias kssh='tmux kill-session -t ssh'
alias kvim='tmux kill-session -t vim'
alias kwork='tmux kill-session -t wiki'

# -------------------------------------------------------------------------- }}}
# {{{ archlinux tlmgr (texlive manager)

export TEXMFDIST='/usr/share/texmf-dist'
alias tlmgr='${TEXMFDIST}/scripts/texlive/tlmgr.pl --usermode'

# -------------------------------------------------------------------------- }}}
