#!/bin/bash
# {{{ Default Browers, File Manager, and 256 colors.

export BROWSER=brave
export FILE=ranger
export TERM=xterm-256color
echoWarning=0

# -------------------------------------------------------------------------- }}}
# {{{ Darwin CLI and LS colors.

if osType "darwin"; then
  export CLICOLOR=1
  export LSCOLORS=GxFxBxDxCxegedabagacad
fi

# -------------------------------------------------------------------------- }}}
# {{{ amber location.

if dirExists ${GITHOME}/amber; then
   AMBERPATH=${GITHOME}/amber
elif dirExists ${BBHOME}/amber; then
     AMBERPATH=${BBHOME}/amber
elif dirExists ${SOUPHOME}/amber; then
     AMBERPATH=${SOUPHOME}/amber
else
  AMBERPATH=""
  [[ $echoWarning == 1 ]] && echo "WARNING: amber is not installed."
fi
export AMBERPATH

if [[ -d ${AMBERPATH} ]]; then
  newfactoryitem() {
    ${AMBERPATH}/bin/newfactoryitem "$@"
  }
fi

# -------------------------------------------------------------------------- }}}
# {{{ autodoc location.

if  dirExists ${GITHOME}/autodoc; then
  AUTODOCPATH=${GITHOME}/autodoc
elif dirExists ${BBHOME}/autodoc; then
   AUTODOCPATH=${BBHOME}/autodoc
elif dirExists ${SOUPHOME}/autodoc; then
   AUTODOCPATH=${SOUPHOME}/autodoc
else
  [[ $echoWarning == 1 ]] && echo "WARNING: autodoc is not installed."
  AUTODOCPATH=""
fi
export AUTODOCPATH

# -------------------------------------------------------------------------- }}}
# {{{ docbld location and function.  These must go together.

if dirExists ${GITHOME}/docbld; then
  DOCBLDPATH=${GITHOME}/docbld
elif dirExists ${BBHOME}/docbld; then
    DOCBLDPATH=${BBHOME}/docbld
elif dirExists ${SOUPHOME}/docbld; then
    DOCBLDPATH=${SOUPHOME}/docbld
else
  [[ $echoWarning == 1 ]] && echo "WARNING: docbld is not installed."
  DOCBLDPATH=""
fi
export DOCBLDPATH

# -------------------------------------------------------------------------- }}}
# {{{ emend location.

if dirExists ${GITHOME}/emend; then
   EMENDPATH=${GITHOME}/emend
elif dirExists ${BBHOME}/emend; then
     EMENDPATH=${BBHOME}/emend
elif dirExists ${SOUPHOME}/emend; then
     EMENDPATH=${SOUPHOME}/emend
else
  EMENDPATH=""
  [[ $echoWarning == 1 ]] && echo "WARNING: emend is not installed."
fi
export EMENDPATH

if [[ -d ${EMENDPATH} ]]; then
  newcomponent() {
    ${EMENDPATH}/bin/newcomponent "$@"
  }
fi

# -------------------------------------------------------------------------- }}}
# {{{ Editor.

export MANWIDTH=76
if osType "msys"; then
  EDITOR=$(which vim)
elif programExists nvim; then
  EDITOR=$(which nvim)
  export MANPAGER='nvim +Man!'
else
  EDITOR=$(which vim)
fi
export EDITOR

# -------------------------------------------------------------------------- }}}
# {{{ emend location and function.  These must go together.

if dirExists ${GITHOME}/emend; then
   EMENDPATH=${GITHOME}/emend
else
  EMENDPATH=""
fi
export EMENDPATH

if [[ -d ${EMENDPATH} ]]; then
  newcomponent() {
    ${EMENDPATH}/bin/newcomponent "$@"
  }
fi

# -------------------------------------------------------------------------- }}}
# {{{ FZF customizations

export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'

# -------------------------------------------------------------------------- }}}
# {{{ HISTCONTROL

export HISTCONTROL=ignoreboth:erasedups

# -------------------------------------------------------------------------- }}}
# {{{ JAVA locations.

if dirExists ${HOME}/build/lclasses/main; then
  CLASSPATH=build/classes/main:build/classes/test
  export CLASSPATH
fi

# -------------------------------------------------------------------------- }}}
# {{{ newdoc location and functions.  These must go together.

if dirExists ${GITHOME}/newdoc; then
   NEWDOCPATH=${GITHOME}/newdoc
elif dirExists ${BBHOME}/newdoc; then
   NEWDOCPATH=${BBHOME}/newdoc
elif dirExists ${SOUPHOME}/newdoc; then
    NEWDOCPATH=${SOUPHOME}/newdoc
else
   [[ $echoWarning == 1 ]] && echo "WARNING: newdoc is not installed."
  NEWDOCPATH=""
fi
export NEWDOCPATH

if [[ -d ${NEWDOCPATH} ]]; then
  newdoc() {
    ${NEWDOCPATH}/newdoc "$@"
  }
fi

# -------------------------------------------------------------------------- }}}
# {{{ X11 display type.

if osType "linux"; then
  export DISPLAY=:0
fi

# -------------------------------------------------------------------------- }}}
# {{{ Lock my Windows environment variables.  Don't ask, Don't tell!!!

if osType "msys"; then
  if hostName "USLK"; then
    export HOME=/c/Users/${USERNAME}
    export HOMEDRIVE=/c
    export HOMEPATH=/c/Users/${USERNAME}
    export GIT_HOME=/c/Users/${USERNAME}/git
    export HOMESHARE=/c
  fi
fi

# -------------------------------------------------------------------------- }}}
