#!/bin/bash 
# ------------------------------------------------------------------------------
# Linux style machines.
# ------------------------------------------------------------------------------
if osType "darwin" \
|| osType "linux"  \
|| osType "msys"; then
    prependToPath ${HOME}/git/dotfiles/bin
    prependToPath ${HOME}/.vim/bundle/vim-superman/bin
    appendToPath  ${HOME}/usr/local/texlive/2020/bin/x85_64-linux

    appendToManPath  /usr/local/texlive/2020/texmf-dist/doc/man

    appendToInfoPath /usr/local/texlive/2020/texmf-dist/doc/info
fi

# ------------------------------------------------------------------------------
# Linux only machines.
# ------------------------------------------------------------------------------
if osType "linux"; then
    appendToPath ${HOME}/.rbenv/bin
    eval "$(rbenv init -)"
fi


# ------------------------------------------------------------------------------
# msys style machines 
# ------------------------------------------------------------------------------
if osType "msys"; then
  appendToPath /mingw64/bin
  appendToPath /c/Program\ Files/MiKTeX\ 2.9/miktex/bin/x64
  appendToPath /c/ProgramData/chocolatey/bin
  appendToPath /c/tools/ruby27/bin
  appendToPath /c/ProgramData/chocolatey/bin
  appendToPath /c/ProgramData/chocolatey/lib/fzf/tools
  appendToPath /c/Strawberry/c/bin
  appendToPath /c/Strawberry/perl/site/bin
  appendToPath /c/Strawberry/perl/bin
fi
