#!/bin/bash
# {{{ Linux style machines.

if osType "darwin" \
|| osType "linux"  \
|| osType "msys"; then
    prependToPath ${HOME}/git/dotfiles/bin
fi

# -------------------------------------------------------------------------- }}}
# {{{ Linux only machines.

ruby_version='3.0.2'
win10_user='mmspghoward'
if osType "linux"; then
    prependToPath ${HOME}/.rbenv/bin
    prependToPath ${HOME}/.rbenv/versions/${ruby_version}/bin
    prependToPath ${HOME}/.cargo/bin
    prependToPath /mnt/c/Users/${win10_user}/AppData/Local/SumatraPDF
    [[ ":$PATH:" != *"${HOME}/.rbenv/bin"* ]] && eval "$(rbenv init -)"
fi

# -------------------------------------------------------------------------- }}}
# {{{ msys style machines

if osType "msys"; then
  appendToPath /mingw64/bin
  appendToPath /c/Program\ Files/MiKTeX/miktex/bin/x64
  appendToPath /c/ProgramData/chocolatey/bin
  appendToPath /c/tools/ruby27/bin
  appendToPath /c/ProgramData/chocolatey/bin
  appendToPath /c/ProgramData/chocolatey/lib/fzf/tools
  appendToPath /c/Strawberry/c/bin
  appendToPath /c/Strawberry/perl/site/bin
  appendToPath /c/Strawberry/perl/bin
fi

# -------------------------------------------------------------------------- }}}
