#!/usr/bin/env bash
NUM_MONITORS=$(hyprctl monitors | grep -c "Monitor")

case "$HOSTNAME" in
  GSA-AXA89M)
            if [ "$NUM_MONITORS" -eq 1 ]; then
              monitors=~/.config/hypr/layout/high-res-laptop.conf
            elif [ "$NUM_MONITORS" -eq 2 ]; then
              monitors=~/.config/hypr/layout/38inch-monitor-and-laptop.conf
            else
              monitors=~/.config/hypr/layout/high-res-laptop.conf
            fi
            ;;
       Ninja)
            monitors=~/.config/hypr/layout/high-res-laptop.conf
            ;;
        Tank)
            monitors=~/.config/hypr/layout/3-27inch-monitors.conf
            ;;
        Zero)
            monitors=~/.config/hypr/layout/low-res-laptop.conf
            ;;
     *) echo
            monitors=~/.config/hypr/layout/high-res-laptop.conf
            ;;
esac


cp $monitors ~/.config/hypr/monitors.conf
