"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
command_timeout = 200

format = """
[$username](bold green)\
[@](bold yellow)\
[$hostname](bold purple)\
[:](bold yellow)\
$directory\
$git_branch$git_status
$linebreak\
$character\
"""

[character]
success_symbol = '[󰘧](bold cyan)'
error_symbol = '[󰘧](bold red)'

[username]
show_always = true
format = '$user'

[hostname]
ssh_only = false
format = '$hostname'

[directory]
truncation_length = 0
truncate_to_repo = false
style = 'bold cyan'

[git_branch]
symbol = " "
format = '\[[$branch$symbol]($style)'
style = "bold purple"

[git_status]
format = '[$up_to_date$ahead$behind$diverged$conflicted$staged$modified$deleted$renamed$typechanged$untracked$stashed]($style)\]'
style = 'bold cyan'

ahead = '|⇡ ${count}'
behind = '|⇣ ${count}'
conflicted = '|'
deleted = '|🗑 ${count}'
diverged = '|⇕⇡ ${ahead_count}⇣${behind_count}'
up_to_date = '|'
modified = '| ${count}'
renamed = '|» ${count}'
staged = '| ● ${count}'
stashed = '|󰏖  ${count}'
typechanged = '|T ${count}'
untracked = ' |🤷 ${count}'
