monitor=DP-4,5120x2160@165,0x0,1

workspace=1,monitor:DP-4,persistent:true
workspace=2,monitor:DP-4,persistent:true
workspace=3,monitor:DP-4,persistent:true
workspace=4,monitor:DP-4,persistent:true
workspace=5,monitor:DP-4,persistent:true
workspace=6,monitor:DP-4,persistent:true
workspace=7,monitor:DP-4,persistent:true
workspace=8,monitor:DP-4,persistent:true
workspace=9,monitor:DP-4,persistent:true
workspace=10,monitor:DP-4,persistent:true
