#!/bin/sh

# Simple wallpaper.
feh --bg-scale $HOME/.config/wallpaper/. &

# Swap keys and left handed mouse.
setxkbmap -option caps:swapescape &
xmodmap -e "pointer = 3 2 1 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 4 5"

# Hotkeys
sxhkd &

# Desktops
if [[ $HOSTNAME =~ "Monk" ]]; then
  xrandr --output HDMI-0 --mode 2560x1440 --pos    0x0 --rotate normal \
         --output DP-0   --mode 2560x1440 --pos 2560x0 --rotate normal \
         --output DP-2   --mode 2560x1440 --pos 5120x0 --rotate normal
  bspc monitor HDMI-0 -d 1 2 3 4
  bspc monitor DP-0   -d 5 6 7
  bspc monitor DP-2   -d 8 9 10
else
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

# Polybar & Picom
$HOME/.config/polybar/launch.sh
$HOME/.config/picom/launch.sh
$HOME/.config/dunst/launch.sh

# Extra programs to launch.
conky -c $HOME/.config/bspwm/system-overview &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
volumeicon &

# Host specific.
if [[ $HOSTNAME =~ "Monk" ]]; then
  dex $HOME/.config/autostart/arcolinux-welcome-app.desktop
  blueberry-tray &
  nm-applet &
  pamac-tray &
  xfce4-power-manager &
fi

# BSPWM configuration
bspc config border_width         1
bspc config window_gap           3
bspc config top_padding          30
bspc config bottom_padding       3
bspc config left_padding         3
bspc config right_padding        3
bspc config single_monocle       truew
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# BSPWM coloring
bspc config normal_border_color   "# 4c566a"
bspc config active_border_color   "# 1e1e1e"
bspc config focused_border_color  "# 5e81ac"
bspc config presel_feedback_color "# 5e81ac"

# Floating applications
bspc rule -a arandr                   state=floating
bspc rule -a Arcolinux-tweak-tool.py  state=floating
bspc rule -a Arcolinux-welcome-app.py state=floating
bspc rule -a alacritty                state=floating
bspc rule -a brave                    state=floating
bspc rule -a xfce4-settings-manager   state=floating
bspc rule -a xfce4-terminal           state=floating

# Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

# open applications on specific workspaces
bspc rule -a "Microsoft Teams - Preview" desktop='^1'
bspc rule -a Thunderbird                 desktop='^1'

bspc rule -a discord desktop='^2'
bspc rule -a Slack   desktop='^2'

bspc rule -a onlyoffice-desktopeditors desktop='^3'

bspc rule -a obs desktop='^4'

bspc rule -a dbeaver  desktop='^0'
