#!/bin/bash
# {{{ Simple run function.

run() { if ! pgrep -f "$1"; then "$@" & fi }

# -------------------------------------------------------------------------- }}}
# {{{ Start Super X Hot Key Deamon (sxhkd) and mouse settings first.

"$HOME"/.config/sxhkd/launch.sh
run numlockx off
run setxkbmap -option caps:swapescape
run xmodmap -e "pointer = 3 2 1 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"
"$HOME"/.config/alacritty/fontsize

# -------------------------------------------------------------------------- }}}
# {{{ Configure physical displays.

# Desktops
if [[ $HOSTNAME =~ "DarkKnight" ||
      $HOSTNAME =~ "Monk" ||
      $HOSTNAME =~ "Warrior" ]] \
	; then

# Three 27" monitors
	xrandr \
    --output HDMI-1 --mode 2560x1440 --pos 0x0    --rotate normal \
    --output DP-1   --mode 2560x1440 --pos 2560x0 --rotate normal \
		--output DP-2   --mode 2560x1440 --pos 5120x0 --rotate normal
	bspc monitor HDMI-1 -d 1 2 3 4
	bspc monitor DP-1 -d 5 6 7
	bspc monitor DP-2 -d 8 9 10

  # One 27" Monitor and One 70" Display
	# xrandr \
    # --output DP-1   --mode 2560x1440 --pos 0x0 --rotate normal --primary \
    # --output HDMI-1 --mode 4096x2160 --pos 0x0 --rotate normal --above DP-1
	# bspc monitor DP-1   -d 6 7 8 9 10
	# bspc monitor HDMI-1 -d 1 2 3 4 5

  # # One 27" Monitor
	# xrandr \
  #   --output DP-1   --mode 2560x1440 --pos 0x0 --rotate normal --primary
	# bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9 10

  bspc rule -a Scratchpad state=floating rectangle=800x600+880+400
  bspc rule -a okular     state=floating rectangle=1278x1440+6400+33
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
  bspc rule -a Scratchpad state=floating rectangle=800x600+560+240
  bspc rule -a okular     state=floating rectangle=958x1044+958+33
fi
# -------------------------------------------------------------------------- }}}
# {{{ Simple wallpaper.

run feh --bg-scale "$HOME"/.config/wallpaper/*

# -------------------------------------------------------------------------- }}}
# {{{ Polybar, Picom, dunst, and volumicon

"$HOME"/.config/polybar/launch.sh
"$HOME"/.config/picom/launch.sh
"$HOME"/.config/dunst/launch.sh
"$HOME"/.config/volumeicon/launch.sh

# -------------------------------------------------------------------------- }}}
# {{{ Extra programs to launch.

run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
run dex "$HOME"/.config/autostart/arcolinux-welcome-app.desktop
run blueberry-tray
run nm-applet
run pamac-tray
run xfce4-power-manager

# 2022.02.22 - Disable conky.  See if you miss it.
# run conky -c "$HOME"/.config/bspwm/system-overview

# -------------------------------------------------------------------------- }}}
# {{{ BSPWM configuration

bspc config border_width 1
bspc config borderless_monocle false
bspc config bottom_padding 1
bspc config focus_follows_pointer true
bspc config gapless_monocle true
bspc config left_padding 0
bspc config merge_overlapping_monitors true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_modifier mod4
bspc config remove_disabled_monitors true
bspc config right_padding 0
bspc config single_monocle true
bspc config split_ratio 0.50
bspc config top_padding 33
bspc config window_gap 0

# -------------------------------------------------------------------------- }}}
# {{{ BSPWM coloring

bspc config active_border_color "#4682B4"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#5e81ac"

# -------------------------------------------------------------------------- }}}
# {{{ Window state and flag rules

bspc rule -a arandr state=floating
bspc rule -a Arcolinux-tweak-tool.py state=floating
bspc rule -a Arcolinux-welcome-app.py state=floating

bspc rule -a xfce4-appfinder state=floating flag=sticky
bspc rule -a xfce4-settings-manager state=floating flag=sticky
bspc rule -a Zathura state=tiled

# -------------------------------------------------------------------------- }}}
# {{{ open applications on specific workspaces


bspc rule -a HEY desktop='^2'

bspc rule -a "ONLYOFFICE Desktop Editors" desktop='^3'

bspc rule -a obs desktop='^4'

bspc rule -a Shotcut desktop='^6'

bspc rule -a "Microsoft Teams - Preview" desktop='^8'

bspc rule -a discord desktop='^9'
bspc rule -a Slack desktop='^9'

bspc rule -a dbeaver desktop='^0'

# -------------------------------------------------------------------------- }}}
