#!/bin/bash
cloneRepo() {
  cd ~/git
  git clone https://github.com/$1.git
}

# My repositories
cloneRepo Traap/amber
cloneRepo Traap/autodoc
cloneRepo Traap/docbld
cloneRepo Traap/dotfiles
cloneRepo Traap/emend-computer
cloneRepo Traap/newdoc
cloneRepo Traap/ssh
cloneRepo Traap/tmux
cloneRepo Traap/vim

# Other repos
# cloneRepo LukeSmithxyz/voidrice
# cloneRepo LukeSmithxyz/st
