#!/bin/bash
repos=()
repos+=('soup/amber')
repos+=('soup/autodoc')
repos+=('soup/docbld')
repos+=('soup/newdoc')
repos+=('rdtest/autodhf')
#repos+=('~gary.howard/fk')
repos+=('~gary.howard/ryder')

clone() {
  arr=("$@")
  for r in "${arr[@]}"
  do
    time git clone ssh://git@bitbucket.fkrnd.com:7999/$r.git
  done
}

clone ${repos[@]}
