#!/bin/bash
repos=(amber autodoc docbld dotfiles  newdoc)

clone() {
  arr=("$@")
  for r in "${arr[@]}"
  do
    git clone --depth 1 ssh://git@10.2.0.235:7999/soup/$r.git
  done
}

clone ${repos[@]}
