#!/usr/bin/env bash
# pacman packages

if [[ ${pacmanPackagesFlag:-false} == true ]]; then
  log_info 'Install pacman packages.'

  pacman_packages=(
    "cmake"
    "docker"
    "ghostty"
    "luacheck"
    "meld"
    "ninja"
    "openssh"
    "openssl"
    "python"
    "python-pynvim"
    "screenkey"
    "selene"
    "slop"
    "stylua"
    "tmux"
    "unzip"
    "vim"
    "which"
  )

  sudo pacman -Syu --noconfirm --needed "${pacman_packages[@]}"
  sudo pacman -Fy
else
  log_info 'pacman packages skipped.'
fi
