#!/usr/bin/env bash
# yay packages

if [[ ${yayPackagesFlag:-false} == true ]]; then
  log_info 'Install yay packages.'

  yay_packages=(
    "fdfind"
    "flameshot"
    "freerdp"
    "fzf"
    "graphviz"
    "hey-mail-bin"
    "imagemagick"
    "jq"
    "lazygit"
    "luarocks"
    "npm"
    "pandoc"
    "python-pip"
    "teams"
    "tldr"
    "visual-studio-code-bin"
    "yazi"
  )

  yay -Sy --noconfirm --needed "${yay_packages[@]}"
else
  log_info 'yay packages skipped.'
fi
