#!/usr/bin/env bash
# gits

if [[ ${gitsFlag:-false}  == true ]]; then
  log_info 'Installing gits.'
  url="https://raw.githubusercontent.com/Traap/gits/master/install.sh"
  /bin/bash -c "$(curl -fsSL $url)"
else
  log_info 'Gits skipped.'
fi
