#!/usr/bin/env bash
# bashrc

if [[ $bashrcFlag == true ]]; then
  say 'Install .bashrc.'
  echo "# All the default Omarchy aliases and functions" > ~/.bashrc
  echo "source ~/.local/share/omarchy/default/bash/rc"  >> ~/.bashrc

  echo ""                                               >> ~/.bashrc
  echo "# Traap's bash personalization"                 >> ~/.bashrc
  echo "source ~/git/dotfiles/bash/bashrc"              >> ~/.bashrc

  echo ""                                               >> ~/.bashrc
  echo "# Don't mess with my .inpurtc"                  >> ~/.bashrc
  echo "bind -f ~/.inputrc"                             >> ~/.bashrc
else
  say '.bashrc skipped.'
fi
