#!/usr/bin/env bash
# openssh

if [[ ${openSSLFlag:-false} == true ]]; then
  log_info 'Install openssl.'

  log_info "Installing OpenSSH and OpenSSL..."
  sudo pacman -Sy --noconfirm --needed openssh openssl

  log_info "Enabling and starting sshd service..."
  sudo systemctl enable sshd.service
  sudo systemctl start sshd.service

  log_info "Checking sshd status..."
  sudo systemctl --no-pager --full status sshd.service || true

  log_info "Verifying installed versions"
  ssh -V
  openssl version
else
  log_info 'openssl skipped.'
fi

