#!/usr/bin/env bash
# openssh

if [[ $openSSLFlag == true ]]; then
  say 'Install openssl.'

  say "Installing OpenSSH and OpenSSL..."
  sudo pacman -Sy --noconfirm --needed openssh openssl

  say "Enabling and starting sshd service..."
  sudo systemctl enable sshd.service
  sudo systemctl start sshd.service

  say "Checking sshd status..."
  sudo systemctl --no-pager --full status sshd.service || true

  say "Verifying installed versions"
  ssh -V
  openssl version
else
  say 'openssl skipped.'
fi

