#!/usr/bin/env bash
# sshhostkeys

if [[ ${sshHostKeyFlag:-false} == true ]]; then
  log_info 'Install ssh host keys.'
  yay -S ssh-keygen
  sshDir=~/git/ssh
  mkdir     -pv $sshDir
  ln       -fsv $sshDir  ~/.ssh
  ssh-keygen -f $sshDir/$HOSTNAME
else
  log_info 'ssh host keys skipped.'
fi
