#!/usr/bin/env bash
# nvims

if [[ ${nvimsFlag:-false} == true ]]; then
  log_info 'Installing nvims.'
  url="https://raw.githubusercontent.com/Traap/nvims/master/install.sh"
  /bin/bash -c "$(curl -fsSL $url)"
else
  log_info 'nvims skipped.'
fi
