#!/usr/bin/env bash
# nvims

if [[ $nvimsFlag == true ]]; then
  say 'Installing nvims.'
  url="https://raw.githubusercontent.com/Traap/nvims/master/install.sh"
  /bin/bash -c "$(curl -fsSL $url)"
else
  say 'nvims skipped.'
fi
