#!/usr/bin/env bash
# mirrors
if [[ $mirrorFlag == true ]]; then
  say 'Updating archlinux mirrors.'
  sudo pacman-key --init
  sudo pacman-key --populate archlinux
  sudo pacman -Sy --noconfirm reflector
  reflector -c "United States" -f 12 -l 10 -n 12  --save /etc/pacman.d/mirrorlist
else
  say 'Skipping archlinux mirrors.'
fi
