#!/usr/bin/env bash
# mirrors
if [[ ${mirrorFlag:-fals}== true ]]; then
  log_info 'Updating archlinux mirrors.'
  sudo pacman-key --init
  sudo pacman-key --populate archlinux
  sudo pacman -Sy --noconfirm reflector
  sudo reflector -c "United States" -f 12 -l 10 -n 12  --save /etc/pacman.d/mirrorlist
else
  log_info 'Skipping archlinux mirrors.'
fi
