#!/usr/bin/env bash
# tmuxplugins

if [[ $tmuxPluginsFlag == true ]]; then
  say 'Installing tmux plugins.'
  src=https://github.com/tmux-plugins/tpm.git
  dst=$cloneRoot/tmux/plugins/tpm
  git clone "$src" "$dst"
  say 'Loading TMUX plugins.'
  ~/.tmux/plugins/tpm/bin/install_plugins
else
  say 'Tmux plugins skipped.'
fi

