#!/usr/bin/env bash
# certificates

if [[ ${certificatesFlag:-false} == true ]]; then
  log_info 'Updating certificates plugins.'
  sudo pacman -S --noconfirm ca-certificates ca-certificates-utils ca-certificates-mozilla
  sudo update-ca-trust
else
  log_info 'Certificate update skipped.'
fi

