#!/usr/bin/env bash
# hyprland

if [[ ${hyprlandFlag:-false} == true ]]; then
  log_info 'Install hyprland.'
  rm    -frv  ~/.config/hypr
  mkdir -pv  ~/config/hypr
  ln    -fsv ~/git/dotfiles/hypr ~/.config/hypr
else
  log_info 'hyprland skipped.' return;
fi

