#!/usr/bin/env bash
# waybar

if [[ ${waybarFlag:-false}== true ]]; then
  log_info 'Install waybar.'
  rm    -frv  ~/.config/waybar
  mkdir -pv  ~/config/waybar
  ln    -fsv ~/git/dotfiles/waybar ~/.config/waybar
else
  log_info 'waybar skipped.'
fi
