#!/usr/bin/env bash
# pacman packages

if [[ $pacmanPackagesFlag == true ]]; then
  say 'Install pacman packages.'

  pacman_packages=(
    "cmake"
    "docker"
    "luacheck"
    "vim"
    "meld"
    "ninja"
    "openssh"
    "openssl"
    "screenkey"
    "selene"
    "slop"
    "stylua"
    "tmux"
    "unzip"
    "which"
  )

  sayAndDo "sudo pacman -Syyu --noconfirm '${pacman_packages[@]}'"
else
  say 'pacman packages skipped.'
fi
