#!/usr/bin/env bash
# pip paackages

if [[ $pipPackagesFlag == true ]]; then
  say 'Install pip packages.'

  pip_packages=(
    "neovim-remote"
  )

  pip install "${pip_packages[@]}"
else
  say 'pip packages skipped.'
fi
