#!/usr/bin/env bash
# pip packages
set -euo pipefail

if [[ ${pipPackagesFlag:-false} == true ]]; then
  log_info "Installing pip packages..."

  pip_packages=(
    neovim-remote
  )

  if ! command -v python3 &>/dev/null; then
    log_fail "python3 not found."
    return
  fi

  python3 -m pip install --upgrade pip
  python3 -m pip install "${pip_packages[@]}" \
    && log_pass "pip packages installed." \
    || log_fail "Failed to install pip packages."
else
  log_info "pip packages skipped."
fi
