#!/usr/bin/env bash
# luarocks paackages

if [[ $luarocksFlag == true ]]; then
  say 'Install luarocks packages.'

  luarocks_packages=(
    "jsregexp"
    )

    "pynvim"
    "neovim-remote"

  pip install "${luarocks_packages[@]}"
else
  say 'luarocks packages skipped.'
fi
