#!/usr/bin/env bash
# luarocks packages

if [[ $luarocksFlag == true ]]; then
  say 'Install luarocks packages.'

  luarocks_packages=(
    "jsregexp"
    "neovim-remote"
    )

  pip install "${luarocks_packages[@]}"
else
  say 'luarocks packages skipped.'
fi
