#!/usr/bin/env bash
# TeX packages

if [[ ${texPackagesFlag:-false}== true ]]; then
  log_info 'Install TeX packages.'

  tex_packages=(
    "texlive-bin"
    "texlive-binextra"
    "texlive-core"
    "texlive-latexextra"
    "texlive-music"
    "texlive-pictures"
    "texlive-plaingeneric"
    "texlive-publishers"
    "texlive-science"
  )

  yay -S --noconfirm "${tex_packages[@]}"
else
  log_info 'TeX packages skipped.'
fi
