#!/usr/bin/env bash

if [[ $sshHostKeyFlag == true ]]; then
  say 'Install ssh host keys.'

  sshDir=~/git/ssh
  mkdir     -pv $sshDir
  ln       -fsv $sshDir  ~/.ssh
  ssh-keygen -f $sshDir/$HOSTNAME
else
  say 'ssh host keys skipped.'
fi
