#!/usr/bin/env bash
# Docker

if [[ ${dockerPacakgesFlag:-false} == true ]]; then
  log_info 'Install docker packages.'

  docker_packages=(
    "docker"
    "docker-buildx"
    "docker-compose"
  )

  sudo pacman -S --noconfirm "${docker_packages[@]}"
  sudo systemctl enable docker.service --now
  sudo systemctl status docker.service 2>/dev/null
else
  log_info 'docker packages skipped.'
fi
