#!/usr/bin/env bash
# omarcnychromiumbrowser
set -euo pipefail

if [[ ${omarchyChromiumBrowserFlag:-false} == true ]]; then
  log_info "Removing Omarcny Chromium Browser..."

  if command -v omarchy-chromium &>/dev/null; then
    sudo pacman -Rns omarchy-chromium
  else
    log_warn "Omarchy Chromium Browser is not installed."
  fi
else
  log_info "Remove Omarchy Chromium Browser skipped."
fi
