#!/usr/bin/env bash
# omarcnychromiumnvim
set -euo pipefail

if [[ ${omarchyNvimFlag:-false} == true ]]; then
  log_info "Removing Omarcny Nvim."

  if command -v omarchy-nvim &>/dev/null; then
    sudo pacman -Rns omarchy-nvim
  else
    log_warn "Omarchy nvim is not installed."
  fi
else
  log_info "Remove Omarcny Nvim skipped."
fi
