#!/usr/bin/env bash
# Check hyprlinkFlag

if [[ $hyprlandFlag == true ]]; then
  say 'Install hyprland.'
  rm    -frv  ~/.config/hypr
  mkdir -pv  ~/config/hypr
  ln    -fsv ~/git/dotfiles/hypr ~/.config/hypr
else
  say 'hyprland skipped.' return;
fi

