#!/usr/bin/env bash
# Check hyprlinkFlag

if [[ $hyprlandFlag == true ]]; then
  say 'Install hyprland.'
else
  say 'hyprland skipped.' return;
fi

# Create a new hyprland configuration directory
rm    -fv  ~/.config/hypr
mkdir -pv  ~/config/hypr
ln    -fsv ~/git/dotfiles/hypr ~/.config/hypr
