#!/usr/bin/env bash

if [[ $waybarFlag == true ]]; then
  say 'Install waybar.'
  rm    -frv  ~/.config/waybar
  mkdir -pv  ~/config/waybar
  ln    -fsv ~/git/dotfiles/waybar ~/.config/waybar
else
  say 'waybar skipped.'
fi
