#!/usr/bin/env bash
# starship

if [[ ${starshipFlag:-false} == true ]]; then
  log_info 'Remove starshp.'

  if command -v starship &>/dev/null; then
    yay -R starship
  else
  log_info 'starship is not installed.'
  fi

else
  log_info 'starship skipped.'
fi
