#!/usr/bin/env bash
# orphaned

if [[ ${orphanedFlag:-false} == true ]]; then
  log_info 'Install orphaned.'
  orphans=$(sudo pacman -Qdtq)
  if [[ -n ${orphahs} ]]; then
    sudo pacman -Rns $orphans
  else
    echo "No orphans found."
  fi
else
  log_info 'orphaned skipped.'
fi
