#!/usr/bin/env bash
# orphaned

if [[ ${orphanedFlag:-false} == true ]]; then
  log_info 'Install orphaned.'
  log_infoAndDo "sudo pacman -Rns $(sudo pacman -Qdtq)"

else
  log_info 'orphaned skipped.'
fi
