#!/usr/bin/env bash
# orphaned

if [[ ${orphanedFlag:-false} == true ]]; then
  log_info 'Install orphaned.'
  sudo pacman --noconfirm  -Rns $(sudo pacman -Qdtq)

else
  log_info 'orphaned skipped.'
fi
