#!/usr/bin/env bash
# seamlesslogin

if [[ $seamlessLoginFlag == true ]]; then
  log_info 'Install seamless login.'
  sudo cp -v omarchy-seamless-login.service /etc/systemd/system/omarchy-seamless-login.servic
  sudo systemctl daemon-reexec
  sudo systemctl daemon-reload
  sudo systemctl restart omarchy-seamless-login.service

else
  log_info 'seamless login skipped.'
fi
