#!/usr/bin/env bash
# {{{ say is a helper function

say() {
  echo '********************'
  echo "${1}"
}

# -------------------------------------------------------------------------- }}}
# {{{ pacman packages

pacman_packages=(
  "cmake"
  "luacheck"
  "vim"
  "meld"
  "ninja"
  "openssh"
  "openssl"
  # "pamac-gtk"
  "screenkey"
  "selene"
  "slop"
  "stylua"
  "tmux"
  "unzip"
  "which"
)

say 'Installing pacman packages.'
sudo pacman -Syyu --noconfirm "${pacman_packages[@]}"

# -------------------------------------------------------------------------- }}}
# {{{ yay packages

yay_packages=(
  "fdfind"
  "flameshot"
  "freerdp"
  "fzf"
  "graphviz"
  "hey-mail-bin"
  "imagemagick"
  "jq"
  "lazygit"
  "luarocks"
  "pandoc"
  "python-pip"
  "tldr"
  "yazi"
)

# yay -Syu --noconfirm "${yay_packages[@]}"

# -------------------------------------------------------------------------- }}}
