#!/usr/bin/env bash
set -euo pipefail

# Run premigration setup first.
source ./functions
source ./config
echo "=== Migration started ==="

# Run migrations
for script in [0-9][0-9]-*; do
  # echo "$script is running."
  source "./$script"
  # echo "$script has completed."
  echo
done

# Done
echo "=== Tha-Tha-Tha That's all, folks! ==="
echo "=== Porky Pig, Looney Toons and Merrie Melodies, 1937 ==="
