#!/usr/bin/env bash
#test-thinkpad
set -euo pipefail

# Save working directory.
pwd=$(pwd)

systemctl status displaylink.service
lsmod | grep evdi
ip link show
ip route get 8.8.8.8
sudo dmesg | grep -E 'r8152|ax88179|cdc_ncm|eth'
sudo dmesg | grep -iE 'displaylink|evdi' | tail -n 25
ls /sys/class/drm/
ls -l /dev/dri/

hyprctl monitors
# Restore working directory
cd "$pwd"
echo "🏁 test-thinkpad completed."
