#!/usr/bin/env bash

# delete symllinks

rm -rfv ~/.config/hypr/config
ln -rfv ~/.config/hypr/layout
ln -rfv ~/.config/hypr/scripts

# create symlinks
ln -fsv ~/git/dotfiles/hypr/config  ~/.config/hypr/config
ln -fsv ~/git/dotfiles/hypr/layout  ~/.config/hypr/layout
ln -fsv ~/git/dotfiles/hypr/scripts ~/.config/hypr/scripts

# Remove Omrachy customer configuration files.
rm -fv  ~/.config/hypr/autostart.conf
rm -fv  ~/.config/hypr/bindings.conf
rm -fv  ~/.config/hypr/envs.conf
rm -fv  ~/.config/hypr/input.conf
rm -fv  ~/.config/hypr/looknfeel.conf
rm -fv  ~/.config/hypr/monitors.conf
