#!/usr/bin/env bash
ln -fsv ~/git/dotfiles/hypr/config  ~/.config/hypr/config
ln -fsv ~/git/dotfiles/hypr/layout  ~/.config/hypr/layout
ln -fsv ~/git/dotfiles/hypr/scripts ~/.config/hypr/scripts

rm -fv  ~/.config/hypr/autostart.conf
rm -fv  ~/.config/hypr/bindings.conf
rm -fv  ~/.config/hypr/envs.conf
rm -fv  ~/.config/hypr/input.conf
rm -fv  ~/.config/hypr/looknfeel.conf
rm -fv  ~/.config/hypr/monitors.conf
