#!/usr/bin/env bash

if [[ $waybarFlag == true ]]; then
  say 'Install waybar.'
  sayAndDo "cp -fv waybar/config.jsonc ~/.config/waybar/."
  sayAndDo "cp -fv waybar/style.css ~/.config/waybar/."
else
  say 'waybar skipped.'
fi
