-- Generated by bindings/generate-session-bindings; do not edit.

if not os.getenv("SESSION_BINDINGS_HOME") then
  print("WARNING: SESSION_BINDINGS_HOME is not defined.")
end

local vars = require("hypr.vars")

local sessions = {
  { key = "D", name = "DataRunner" },
  { key = "N", name = "Neovim" },
  { key = "P", name = "Paperboy" },
  { key = "U", name = "Upgrade" },
  { key = "W", name = "Work" },
  { key = "Y", name = "YouTube" },
  { key = "Z", name = "Zero" },
}

for _, session in ipairs(sessions) do
  local toggle_keys = "ALT + " .. session.key
  local kill_keys = "ALT + SHIFT + " .. session.key

  hl.unbind(toggle_keys)
  o.bind(
    toggle_keys,
    "Toggle " .. session.name,
    vars.bin_home .. "/toggler " .. session.name
  )

  hl.unbind(kill_keys)
  o.bind(
    kill_keys,
    "Kill " .. session.name,
    "tmux kill-session -t " .. session.name
  )
end
