#!/bin/bash
yad \
  --width=530 \
  --height=550 \
  --center \
  --fixed \
  --title="Hyprland Keybindings" \
  --no-buttons \
  --list \
  --column=Key: \
  --column=Description: \
  --column=Command: \
  --timeout=60 \
  --timeout-indicator=right \
  "ESC" "close this app" "" \
  "+A" "Application Finder" "(xfce4-appfinder)" \
  "+E" "" "MS Edge" \
  "+H" "Email" "(Hey)" \
  "+K" "Keystrokes" "(screenkey)" \
  "+L" "Lock" "(swaylock)" \
  "+N" "" "Thunar" \
  "+O" "Office" "(Only Office)" \
  "+Q" "Close focused app" "(kill)" \
  "+R" "Remote Desktop" "(Remmina)" \
  "+Return" "Terminal" "(Ghostty)" \
  "+S" "Screen shot" "(Flameshot)" \
  "+T" "" "MS Teams" \
  "+V" "Screen Recorder" "(OBS)" \
  "+W" "" "LibreWolf" \
  "+X" "Logout" "(archlinux-logout)" \
  "+Shift+e" "power-menu" "(wofi)" \
  "+Shift+c" "Change wallpaper" "(wpaperd)" \
  "+f" "Fullscreen" "Toggles to full screen" \
  "+Shift+f" "Fake fullscreen" "Behave full screen without full screen" \
  "+Shift+Spacebar" "Float" "Toggle windows to float" \
  "" "" "     Window closed in 60 sec."\
