# config/windowrules.conf
windowrule = match:class .*, opacity 1.00 override 1.00 override

# Increase Omarchy default float window size
# windowrule = size 875 600, match:tag floating-window # 0%
# windowrule = size 884 606, match:tag floating-window # 1%
# windowrule = size 893 612, match:tag floating-window # 2%
# windowrule = size 902 618, match:tag floating-window # 3%
# windowrule = size 910 624, match:tag floating-window # 4%
# windowrule = size 918 630, match:tag floating-window # 5%
# windowrule = size 963 660, match:tag floating-window # 10%
# windowrule = size 1007 690, match:tag floating-window # 15%
# windowrule = size 1050 720, match:tag floating-window # 20%
windowrule = size 1094 750, match:tag floating-window # 25%
