#!/bin/bash
# Define directory exports that my_functions use.
BBHOME=$HOME/bb
export BBHOME

CFGHOME=$HOME/.config
export CFGHOME

EDITOR=$(which nvim)
export EDITOR

GITHOME=$HOME/git
export GITHOME

GITPATH=$GITHOME
export GITPATH

DOTHOME=$GITHOME/dotfiles
export DOTHOME

BASHHOME=$DOTHOME/bash
export BASHHOME

BINHOME=$BASHHOME/bin
export BINHOME

NVIMHOME=$GITHOME/nvim.traap
export HOME

SSHHOME=$GITHOME/ssh
export SSHHOME

VIMHOME=$GITHOME/vim
export VIMHOME

WIKIHOME=$GITHOME/wiki
export WIKIHOME

WORKHOME=$GITHOME/gsa
export WORKHOME

YOUTUBEHOME=$GITHOME/youtube
export YOUTUBEHOME

PDF_VIEWER=okular
export PDF_VIEWER

# msys work-around.
if [[ ${OSTYPE} =~ "linux" ]]; then
  # Define functions and paths.
  my_array=("functions" "paths")
  for m in ${my_array[@]}; do
    [[ -f $BASHHOME/my_$m ]] && source $BASHHOME/my_$m
  done

  # Hook into interactive bash.
  [[ -f ~/.bashrc ]] && . ~/.bashrc
fi

# opam configuration
test -r /home/traap/.opam/opam-init/init.sh && . /home/traap/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
