#!/bin/bash

# Define directory exports that my_functions use.
BBHOME=$HOME/bb
export BBHOME

CFGHOME=$HOME/.config
export CFGHOME

GITHOME=$HOME/git
export GITHOME

GITPATH=$GITHOME
export GITPATH

DOTHOME=$GITHOME/dotfiles
export DOTHOME

BASHHOME=$DOTHOME/bash
export BASHHOME

BINHOME=$BASHHOME/bin
export BINHOME

SSHHOME=$GITHOME/ssh
export SSHHOME

# Define functions and paths.
my_array=("functions" "paths")
for m in ${my_array[@]}; do
  [[ -f $BASHHOME/my_$m ]] && source $BASHHOME/my_$m
done

# Load my keys.
sshkeys

# Hook into interactive bash.
[[ -f ~/.bashrc ]] && . ~/.bashrc
