#!/bin/bash
# {{{ Stooges: Honoring Larry, Moe, and Curly ... Nyuk, nyuk, nyuk.
#
# Bash scripting cheatsheet => https://devhints.io/bash

echo "$HOSTNAME running $OSTYPE"

# -------------------------------------------------------------------------- }}}
# {{{ Disable ctrl-s, ctrl-q, and set infinite history.

stty -ixon
HISTSIZE='' HISTFILESIZE=''

# -------------------------------------------------------------------------- }}}
# {{{ shopt

shopt -s autocd         # change to named directory
shopt -s cdspell        # autocorrects cd misspellings
shopt -s cmdhist        # save multi-line commands in history as single line
shopt -s dotglob        # dot file names are included in path expansion.
shopt -s histappend     # do not overwrite history
shopt -s expand_aliases # expand aliases

# -------------------------------------------------------------------------- }}}
# {{{ Customize my shell. Array order matters.

my_array=("functions" "exports" "aliases" "paths" "completions" "prompt")
for m in "${my_array[@]}"; do
  [[ -f "$BASHHOME/my_$m" ]] && __guarded_source "$BASHHOME/my_$m"
done

# Load my keys.
sshkeys

# -------------------------------------------------------------------------- }}}
# {{{ Neovim appname aliases

[[ -f "$HOME/.config/nvims/nvim_appnames" ]] && \
  __guarded_source "$HOME/.config/nvims/nvim_appnames"

# -------------------------------------------------------------------------- }}}
