#!/bin/bash
# {{{ Stooges: Honoring Larry, Moe, and Curly ... Nyuk, nyuk, nyuk.
#
# Bash scripting cheatsheet => https://devhints.io/bash

echo ${HOSTNAME} "running" ${OSTYPE}

# -------------------------------------------------------------------------- }}}
# {{{ Top level exports I used throughout all my scripts.

BBHOME=$HOME/bb
export BBHOME

CFGHOME=$HOME/.config
export CFGHOME

GITHOME=$HOME/git
export GITHOME

GITPATH=$GITHOME
export GITPATH

DOTHOME=$GITHOME/dotfiles
export DOTHOME

BASHHOME=$DOTHOME/bash
export BASHHOME

BINHOME=$BASHHOME/bin
export BINHOME

SSHHOME=$GITHOME/ssh
export SSHHOME

# -------------------------------------------------------------------------- }}}
# {{{ Disable ctrl-s, ctrl-q, and set infinite history.

stty -ixon
HISTSIZE= HISTFILESIZE=

# -------------------------------------------------------------------------- }}}
# {{{ Customize my shell. Array order matters.

my_array=("functions" "exports" "aliases" "paths" "completions" "prompt")

for m in ${my_array[@]}; do
  [[ -f $BASHHOME/my_$m ]] && source $BASHHOME/my_$m
done

# Load my keys.
sshkeys

# -------------------------------------------------------------------------- }}}
