#!/bin/bash
# {{{ Stooges: Honoring Larry, Moe, and Curly ... Nyuk, nyuk, nyuk.
#
# Bash scripting cheatsheet => https://devhints.io/bash

# -------------------------------------------------------------------------- }}}
# {{{ non-login interactive shells.

source_bash_profile_once() {
  if declare -p __bash_profile_once &>/dev/null; then
    return
  fi

  source $BASHHOME/bash_profile

  if ! declare -p __bash_profile_once &>/dev/null; then
    readonly __bash_profile_once=true
  fi
}
source_bash_profile_once

# -------------------------------------------------------------------------- }}}
# {{{ Personal hook.

__guarded_source $BASHHOME/bashrc_personal

# -------------------------------------------------------------------------- }}}
# {{{ Sometime other programs automagically update my bashrc.
#
[[ -f $HOME/traap/.ghcup/env ]] && \
    . $HOME/traap/.ghcup/env

[ -f ~/.fzf.bash ] && . ~/.fzf.bash

[[ -f /usr/share/fzf/completion.bash ]]  && \
    . /usr/share/fzf/completion.bash

[[ -f /usr/share/fzf/key-bindings.bash ]] && \
    . /usr/share/fzf/key-bindings.bash

[[ -f $HOME/.config/lua-language-server/3rd/luamake/luamake ]] && \
      alias luamake=$HOME/.config/lua-language-server/3rd/luamake/luamake

[[ -f $HOME/lib/azure-cli/az.completion ]] && \
    . $HOME/lib/azure-cli/az.completion

[[ -f $HOME/.cargo/env ]] && \
   .  $HOME/.cargo/env

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# TODO: eval after checking for program.
eval "$(uv generate-shell-completion bash)"

# -------------------------------------------------------------------------- }}}
