#!/bin/bash
# {{{ Stooges: Honoring Larry, Moe, and Curly ... Nyuk, nyuk, nyuk.
#
# Bash scripting cheatsheet => https://devhints.io/bash

echo ${HOSTNAME} "running" ${OSTYPE}

# -------------------------------------------------------------------------- }}}
# {{{ Disable ctrl-s, ctrl-q, and set infinite history.

stty -ixon
HISTSIZE= HISTFILESIZE=

# -------------------------------------------------------------------------- }}}
# {{{ Customize my shell. Array order matters.

my_array=("functions" "exports" "aliases" "paths" "completions" "prompt")

for m in ${my_array[@]}; do
  [[ -f $BASHHOME/my_$m ]] && source $BASHHOME/my_$m
done

# Load my keys.
sshkey

# -------------------------------------------------------------------------- }}}
