#!/bin/bash
# {{{ Stooges: Honoring Larry, Moe, and Curly ... Nyuk, nyuk, nyuk.
#
# Bash scripting cheatsheet => https://devhints.io/bash

# -------------------------------------------------------------------------- }}}
# {{{ non-longin interactive shells.

source_bash_profile_once() {
  if [[ -z "$__bash_profile_loaded" ]]; then
    export __bash_profile_loaded=1
    source ~/.bash_profile
  fi
}
source_bash_profile_once

# -------------------------------------------------------------------------- }}}
# {{{ Personal hook.

__guarded_source $HOME/.bashrc_personal

# -------------------------------------------------------------------------- }}}
# {{{ Sometime other programs automagically update my bashrc.
#
[[ -f $HOME/traap/.ghcup/env ]] && \
    . $HOME/traap/.ghcup/env

[ -f ~/.fzf.bash ] && . ~/.fzf.bash

[[ -f /usr/share/fzf/completion.bash ]]  && \
    . /usr/share/fzf/completion.bash

[[ -f /usr/share/fzf/key-bindings.bash ]] && \
    . /usr/share/fzf/key-bindings.bash

[[ -f $HOME/.config/lua-language-server/3rd/luamake/luamake ]] && \
      alias luamake=$HOME/.config/lua-language-server/3rd/luamake/luamake

[[ -f $HOME/lib/azure-cli/az.completion ]] && \
    . $HOME/lib/azure-cli/az.completion

[[ -f $HOME/.cargo/env ]] && \
   .  $HOME/.cargo/env

# -------------------------------------------------------------------------- }}}
