#!/bin/bash
# {{{ Operating system specific settings.

if osType "/darwin"; then
  alias la='ls -A'
  alias ll='ls -lahG'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Vim keybindings.

set -o vi

# -------------------------------------------------------------------------- }}}
# {{{ latexrun is defined when present.

if fileExists $GITHOME/latexrun/latexrun; then
  alias latexrun='$GITHOME/latex/latexrun/latexrun'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Tmux setup.

if fileExists /usr/bin/tmux; then
  alias tmux='tmux -2'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Use bat and exa when they are installed.

[   -f /usr/bin/bat ] && alias 'cat=bat -p'
[   -f /usr/bin/exa ] && alias ls='exa'
[ ! -f /usr/bin/exa ] && alias ls='ls --color=auto'

# -------------------------------------------------------------------------- }}}
# {{{ General purpose aliases.

alias cls='clear'
alias encrypt='$BINHOME/encrypt'
if [[ $(rg --ignore-case '"Ubuntu' /etc/os-release -c) -gt 0 ]]; then
  alias fd='fdfind'
  alias fde='fdfind --no-ignore --extension'
else
  alias fde='fd --no-ignore --extension'
fi
alias fgrep='fgrep --color=auto'
alias ga='git add'
alias gP='git pull'
alias gbp='gits bb pull'
alias gc='git commit -m'
alias gcu='git checkout -- .'
alias ggp='gits git pull'
alias gl7='git logg -7'
alias glg='git log'
alias glgg='git logg'
alias glgi='git logi'
alias gp='git push'
alias grep='grep --color=auto'
alias grh='git reset HEAD'
alias gs='clear && git status'
alias gsuo='git push --set-upstream origin'
alias h='history'
alias help='man'
alias kax='sudo killall Xorg'
alias l1='ls -1'
alias lad='ls -lad .*'
alias las='find . -maxdepth 1 -type l -printf "%p -> %l\n" | sort'
alias lass='find . -type l -printf "%p -> %l\n" | sort'
alias l24='find . -newermt "-24 hours" -ls'
alias me='clear && exec bash'
alias mv='mv -v'
alias n='nvim'
alias nano='nvim'
alias np='nvim +PackerSync'
alias pacmann='sudo pacman --noconfirm -S'
alias rbe='eval "$(rbenv init - n)"'
alias rbn='sudo reboot now'
alias s='source'
alias sa='source $BASHHOME/my_aliases'
alias sdn='sudo shutdown now'
alias se='source $BASHHOME/my_exports'
alias sf='source $BASHHOME/my_functions'
alias sp='source $BASHHOME/my_paths'
alias ssh='ssh -A'
alias ta='tmux attach'
alias xz='nvim -c "let g:tty='\''$(tty)'\''"'

# -------------------------------------------------------------------------- }}}
# {{{ Aliases to folders I visit frequently.

alias .a='cd $BASHHOME'
alias .b='cd $BINHOME'
alias .c='cd $CFGHOME'
alias .d='cd $DOTHOME'
alias .g='cd $GITHOME'
alias Cd='cd $GITHOME/color'
alias Dc='cd $HOME/Documents'
alias Dd='cd $HOME/Downloads'
alias Ld='cd $HOME/.local/share/nvim/lsp_servers'
alias ac='cd $GITHOME/AllanConsulting'
alias bd='cd $GITHOME/bootstrap'
alias gd='cd $GITHOME'
alias hh='cd $GITHOME/HowardHouse'
alias nd='cd $GITHOME/nvim'
alias pd='cd $HOME/.local/share/nvim/site/pack/packer/start'
alias rd='cd $GITHOME/resume'
alias sd='cd $GITHOME/ssh'
alias td='cd $GITHOME/tmux'
alias vb='cd $GITHOME/vim/bundle'
alias vd='cd $GITHOME/vim'
alias wd='cd $GITHOME/wiki'

alias cal='cd $CFGHOME/alacritty'
alias cbs='cd $CFGHOME/bspwm'
alias cdc='cd $CFGHOME/dconf'
alias cdu='cd $CFGHOME/dunst'
alias cki='cd $CFGHOME/kitty'
alias cnv='cd $CFGHOME/nvim'
alias cpi='cd $CFGHOME/picom'
alias cpo='cd $CFGHOME/polybar'
alias cra='cd $CFGHOME/ranger'
alias csx='cd $CFGHOME/sxhkd'
alias cth='cd $CFGHOME/Thunar'

# -------------------------------------------------------------------------- }}}
# {{{ Brew wants me to own usr/local

if osType "darwin"; then
  alias ulo='sudo chown -R $(whoami) /usr/local'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Repeat command are used when I enable my resume editor.

alias rgl='repeat git logg -6'
alias rgs='repeat git status --short'

# -------------------------------------------------------------------------- }}}
# {{{ Perforce defaults.

if osType "linux"; then
  if hostName "Ryder"; then
    alias p4='${P4DISK}/2013.1/p4'
    alias p4d='${P4DISK}/2013.1/p4d'
  fi
fi

# -------------------------------------------------------------------------- }}}
# {{{ File I edit frequently.

alias ,eb='$EDITOR $BASHHOME/bootstrap.vim'
alias ,ec='$EDITOR $GITHOME/ssh/config.vim'
alias ,ed='$EDITOR $GITHOME/vim/custom-dictionary.utf-8.add'
alias ,eg='$EDITOR $GITHOME/ssh/gitconfig'
alias ,en='$EDITOR $GITHOME/vim/nvim.vim'
alias ,ep='$EDITOR $GITHOME/vim/plug.vim'
alias ,em='$EDITOR $GITHOME/vim/minimal-plug.vim'
alias ,et='$EDITOR $GITHOME/tmux/tmux.conf'
alias ,ev='$EDITOR $GITHOME/vim/vimrc'

alias ,ma='$EDITOR $BASHHOME/my_aliases'
alias ,mb='$EDITOR $BASHHOME/bashrc'
alias ,mc='$EDITOR $BASHHOME/my_completions'
alias ,me='$EDITOR $BASHHOME/my_exports'
alias ,mf='$EDITOR $BASHHOME/my_functions'
alias ,mp='$EDITOR $BASHHOME/my_paths'
alias ,mt='$EDITOR $BASHHOME/my_prompt'
alias ,mz='$EDITOR $BASHHOME/bashrc-personal'

alias ,xb='$EDITOR $BASHHOME/bspwmrc'
alias ,xs='$EDITOR $BASHHOME/sxhkdrc'

# -------------------------------------------------------------------------- }}}
# {{{ tmux sessions I frequently use.

alias tao='ao ao'
alias tbash='ao bash'
alias tkjv='ao kjv'
alias tnvim='ao nvim'
alias tsoup='ao soup'
alias tssh='ao ssh'
alias tvim='ao vim'
alias tt='ao t'
alias twiki='ao wiki'

alias kao='tmux kill-session -t ao'
alias kbash='tmux kill-session -t bash'
alias kkjv='tmux kill-session -t kjv'
alias knvim='tmux kill-session -t nvim'
alias ksoup='tmux kill-session -t soup'
alias kssh='tmux kill-session -t ssh'
alias kt='tmux kill-session -t t'
alias kvim='tmux kill-session -t vim'
alias kwiki='tmux kill-session -t wiki'

# -------------------------------------------------------------------------- }}}
# {{{ archlinux tlmgr (texlive manager)

export TEXMFDIST='/usr/share/texmf-dist'
alias tlmgr='${TEXMFDIST}/scripts/texlive/tlmgr.pl --usermode'

# -------------------------------------------------------------------------- }}}
