#!/bin/bash
# {{{ Vim keybindings.

set -o vi

# -------------------------------------------------------------------------- }}}
# {{{ latexrun is defined when present.

if fileExists "$GITHOME"/latexrun/latexrun; then
	alias latexrun='$GITHOME/latex/latexrun/latexrun'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Tmux setup.

if fileExists /usr/bin/tmux; then
	alias tmux='tmux -2'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Use bat and exa when they are installed.

if osType "msys"; then
	alias cat='bat -p'
	alias ls='ls --color=auto'
else
  if osName "Ubuntu"; then
	  [ -f /usr/bin/batcat ] && alias cat='batcat -p'
  else
	  [ -f /usr/bin/bat ] && alias cat='bat -p'
  fi
	[ -f /usr/bin/exa ] && alias ls='exa'
fi

# -------------------------------------------------------------------------- }}}
# {{{ General purpose aliases.

alias cgits='clear && gits'
alias cls='clear'
alias encrypt='$BINHOME/encrypt'
if [[ $(rg --ignore-case '"Ubuntu' /etc/os-release -c 2>/dev/null) -gt 0 ]]; then
	alias fd='fdfind'
	alias fde='fdfind --no-ignore --extension'
else
	alias fde='fd --no-ignore --extension'
fi

alias df='df -h'
alias unlock="sudo rm /var/lib/pacman/db.lck"
alias free="free -mt"
alias uac="sh ~/.bin/main/000*"
alias wget="wget -c"
alias iso="cat /etc/dev-rel | awk -F '=' '/ISO/ {print $2}'"
alias isoo="cat /etc/dev-rel"
alias userlist="cut -d: -f1 /etc/passwd"
alias merge="xrdb -merge ~/.Xresources"
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gP='git pull'
alias ga='git add'
alias gbp='gits -r bb -p'
alias gc='git commit -m'
alias gco.='git checkout -- .'
alias ggp='gits -r git -p'
alias ggw='gits -r work -p'
alias gl7='git logg -7'
alias glg='git log'
alias glgg='git logg'
alias glgi='git logi'
alias gp='git push'
alias grep='grep --color=auto'
alias grh='git reset HEAD'
alias gs='clear && git status'
alias gsuo='git push --set-upstream origin'
alias h='history'
alias help='man'
alias kax='sudo killall Xorg'
alias l.="ls -A | grep -E '^\.'"
alias l1='ls -1'
alias l='ls'
alias la='ls -a'
alias ll='ls -la'
alias lad='ls -lad .*'
alias las='find . -maxdepth 1 -type l -printf "%p -> %l\n" | sort'
alias lass='find . -type l -printf "%p -> %l\n" | sort'
alias ll='ls -la'
alias l24='find . -newermt "-24 hours" -ls'
alias me='clear && exec bash'
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
alias mv='mv -v'
alias n='nvim'
alias nano='$EDITOR'
alias norc='$EDITOR -u NORC'
alias np='nvim +PackerSync'
alias pacman='sudo pacman --noconfirm -S'
alias rbe='eval "$(rbenv init - n)"'
alias rbn='sudo reboot now'
alias rgits='repeat gits'
alias sde='sudoedit'
alias sdn='sudo shutdown now'
alias slv='switchNeovim'
alias snv='switchNeovim'
alias ssh='ssh -A'
alias ta='tmux attach'
alias tl='tmux ls'
alias tlmgr='${TEXMFDIST}/scripts/texlive/tlmgr.pl'
alias v='vim'
alias vg='vim +G'
alias vp='vim +PlugUpdate'
alias wlv='cat ~/.lunarvim_in_use_okay_to_delete'
alias wnv='cat ~/.neovim_in_use_okay_to_delete'
alias xz='$EDITOR -c "let g:tty='\''$(tty)'\''"'

# -------------------------------------------------------------------------- }}}
# {{{ Aliases to folders I visit frequently.

alias .a='cd $BASHHOME'
alias .b='cd $BINHOME'
alias .c='cd $CFGHOME'
alias .d='cd $DOTHOME'
alias .g='cd $GITHOME'
alias .h='cd $CFGHOME/hypr'
alias Cd='cd $GITHOME/color'
alias Dc='cd $HOME/Documents'
alias Dd='cd $HOME/Downloads'
alias Ld='cd $HOME/.local/share/nvim/lsp_servers'
alias ac='cd $GITHOME/AllanConsulting'
alias bd='cd $GITHOME/bootstrap'
alias gd='cd $GITHOME'
alias hh='cd $GITHOME/HowardHouse'
alias ic='cd $HOME/img-clip'

if osType "msys"; then
  alias nd='cd AppData/Local/nvim'
else
  alias nd='cd $GITHOME/nvim.traap'
fi

alias pd='cd $HOME/.local/share/nvim/site/pack/packer/start'
alias rd='cd $GITHOME/resume'
alias sd='cd $GITHOME/ssh'
alias td='cd $GITHOME/tmux'
alias vb='cd $GITHOME/vim/bundle'
alias vd='cd $GITHOME/vim'
alias wd='cd $WIKIHOME'
alias wk='cd $WORKHOME'
alias yd='cd $YOUTUBEHOME'

alias cal='cd $CFGHOME/alacritty'
alias cbs='cd $CFGHOME/bspwm'
alias cdc='cd $CFGHOME/dconf'
alias cdu='cd $CFGHOME/dunst'
alias chy='cd $CFGHOME/hybr'
alias cki='cd $CFGHOME/kitty'
alias cma='cd $CFGHOME/mako'
alias cnv='cd $CFGHOME/nvim'
alias cpi='cd $CFGHOME/picom'
alias cpo='cd $CFGHOME/polybar'
alias cra='cd $CFGHOME/ranger'
alias csx='cd $CFGHOME/sxhkd'
alias cth='cd $CFGHOME/Thunar'
alias cwb='cd $CFGHOME/waybar'
alias cwf='cd $CFGHOME/wayfire'
alias cwo='cd $CFGHOME/wofi'

# -------------------------------------------------------------------------- }}}
# {{{ shutdown or reboot or lock screen.

alias ssn="sudo shutdown now"
alias sr="sudo reboot"
alias bls="betterlockscreen -u /usr/share/backgrounds/arcolinux/"

# -------------------------------------------------------------------------- }}}
# {{{ Brew wants me to own usr/local

if osType "darwin"; then
	alias ulo='sudo chown -R $(whoami) /usr/local'
fi

# -------------------------------------------------------------------------- }}} {{{ Repeat command are used when I enable my resume editor.

alias rgl='repeat git logg -6'
alias rgs='repeat git status --short'

# -------------------------------------------------------------------------- }}}
# {{{ Archlinux Packages

# Recent Installed Packages
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"
alias riplong="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -3000 | nl"

# Cleanup orphaned packages
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'

# -------------------------------------------------------------------------- }}}
# {{{ Important configuration files

alias nconfgrub="sudo nvim /boot/grub/grub.cfg"
alias ngrub="sudo nvim /etc/default/grub"
alias nlightdm="sudo nvim /etc/lightdm/lightdm.conf"
alias nmirrorlist="sudo nvim /etc/pacman.d/mirrorlist"
alias nmkinitcpio="sudo nvim /etc/mkinitcpio.conf"
alias noblogout="sudo nvim /etc/oblogout.conf"
alias npacman="sudo nvim /etc/pacman.conf"
alias nslim="sudo nvim /etc/slim.conf"

# -------------------------------------------------------------------------- }}}
# {{{ gpg

# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"

# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# -------------------------------------------------------------------------- }}}
# {{{ Job control

# get the error messages from journalctl
alias jctl="journalctl -p 3 -xb"

# -------------------------------------------------------------------------- }}}
# {{{ Perforce defaults.

if osType "linux"; then
	if hostName "Ryder"; then
		alias p4='${P4DISK}/2013.1/p4'
		alias p4d='${P4DISK}/2013.1/p4d'
	fi
fi

# -------------------------------------------------------------------------- }}}
# {{{ File I edit frequently.  These aliases mirror keybinds used in Vim.
#     TODO: 2023.12.22 Consider pruning this list.

alias ,ec='$EDITOR $GITHOME/ssh/config.vim'
alias ,ed='$EDITOR $GITHOME/vim/custom-dictionary.utf-8.add'
alias ,eg='$EDITOR $GITHOME/ssh/gitconfig'
alias ,en='$EDITOR $GITHOME/nvim.traap/init.lua'
alias ,em='$EDITOR $GITHOME/vim/minimal-plug.vim'
alias ,et='$EDITOR $GITHOME/tmux/tmux.conf'
alias ,ev='$EDITOR $GITHOME/vim/vimrc'

alias ,ma='$EDITOR $BASHHOME/my_aliases'
alias ,mb='$EDITOR $BASHHOME/bashrc'
alias ,mc='$EDITOR $BASHHOME/my_completions'
alias ,me='$EDITOR $BASHHOME/my_exports'
alias ,mf='$EDITOR $BASHHOME/my_functions'
alias ,mp='$EDITOR $BASHHOME/my_paths'
alias ,mt='$EDITOR $BASHHOME/my_prompt'
alias ,mz='$EDITOR $BASHHOME/bashrc-personal'

alias ,xb='$EDITOR $DOTHOME/bspwm/bspwmrc'
alias ,xs='$EDITOR $DOTHOME/sxhkd/sxhkdrc'

# -------------------------------------------------------------------------- }}}
# {{{ tmux sessions I frequently use.

alias tao='ao ao'
alias tbash='ao bash'
alias tkjv='ao kjv'
alias tnvim='ao Nvim'
alias tsoup='ao soup'
alias tvim='ao vim'
alias tspad='ao Scratchpad'
alias td='ao d'
alias th='ao h'
alias tt='ao t'
alias tupd='ao Upgrade'
alias twiki='ao Wiki'
alias tyt='ao YouTube'
alias tz='ao Zero'

alias kao='tmux kill-session -t ao'
alias kbash='tmux kill-session -t bash'
alias kkjv='tmux kill-session -t kjv'
alias knvim='tmux kill-session -t Nvim'
alias kspad='tmux kill-session -t Scratchpad'
alias kd='tmux kill-session -t d'
alias kh='tmux kill-session -t h'
alias kt='tmux kill-session -t t'
alias kupd='tmux kill-session -t Upgrade'
alias kvim='tmux kill-session -t vim'
alias kwiki='tmux kill-session -t Wiki'
alias kyt='tmux kill-session -t YouTube'
alias kz='tmux kill-session -t Zero'

# -------------------------------------------------------------------------- }}}
# {{{ archlinux tlmgr (texlive manager)

export TEXMFDIST='/usr/share/texmf-dist'
alias tlmgr='${TEXMFDIST}/scripts/texlive/tlmgr.pl --usermode'

# -------------------------------------------------------------------------- }}}
# {{{ WSL (Windows Subsystem for Linux)

# Windows paths are appended to PATH when WSL is present.

if [[ -n $WSL_DISTRO_NAME ]]; then
	alias wsl=wsl.exe
fi

# -------------------------------------------------------------------------- }}}
