#!/bin/bash
# {{{ Operating system specific settings.

if osType "/darwin"; then
	alias la='ls -A'
	alias ll='ls -lahG'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Vim keybindings.

set -o vi

# -------------------------------------------------------------------------- }}}
# {{{ latexrun is defined when present.

if fileExists "$GITHOME"/latexrun/latexrun; then
	alias latexrun='$GITHOME/latex/latexrun/latexrun'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Tmux setup.

if fileExists /usr/bin/tmux; then
	alias tmux='tmux -2'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Use bat and exa when they are installed.

if osType "msys"; then
	alias cat='bat -p'
	alias ls='ls --color=auto'
else
  if osName "Ubuntu"; then
	  [ -f /usr/bin/batcat ] && alias cat='batcat -p'
  else
	  [ -f /usr/bin/bat ] && alias cat='bat -p'
  fi
	[ -f /usr/bin/exa ] && alias ls='exa'
	[ ! -f /usr/bin/exa ] && alias ls='ls --color=auto'
fi

# -------------------------------------------------------------------------- }}}
# {{{ General purpose aliases.

alias cgits='clear && gits'
alias cls='clear'
alias encrypt='$BINHOME/encrypt'
if [[ $(rg --ignore-case '"Ubuntu' /etc/os-release -c 2>/dev/null) -gt 0 ]]; then
	alias fd='fdfind'
	alias fde='fdfind --no-ignore --extension'
else
	alias fde='fd --no-ignore --extension'
fi
alias fgrep='fgrep --color=auto'
alias ga='git add'
alias gP='git pull'
alias gbp='gits bb pull'
alias gc='git commit -m'
alias gco.='git checkout -- .'
alias ggp='gits git pull'
alias gl7='git logg -7'
alias glg='git log'
alias glgg='git logg'
alias glgi='git logi'
alias gp='git push'
alias grep='grep --color=auto'
alias grh='git reset HEAD'
alias gs='clear && git status'
alias gsuo='git push --set-upstream origin'
alias h='history'
alias help='man'
alias kax='sudo killall Xorg'
alias l1='ls -1'
alias lad='ls -lad .*'
alias las='find . -maxdepth 1 -type l -printf "%p -> %l\n" | sort'
alias lass='find . -type l -printf "%p -> %l\n" | sort'
alias lg='lvim +G'
alias l24='find . -newermt "-24 hours" -ls'
alias me='clear && exec bash'
alias mv='mv -v'
alias n='nvim'
alias nano='$EDITOR'
alias ng='nvim +G'
alias np='nvim +PackerSync'
alias pacmann='sudo pacman --noconfirm -S'
alias rbe='eval "$(rbenv init - n)"'
alias rbn='sudo reboot now'
alias rgits='repeat gits'
alias s='source'
alias sa='source $BASHHOME/my_aliases'
alias sde='sudoedit'
alias sdn='sudo shutdown now'
alias se='source $BASHHOME/my_exports'
alias sf='source $BASHHOME/my_functions'
alias slv='switchNeovim'
alias snv='switchNeovim'
alias sp='source $BASHHOME/my_paths'
alias ssh='ssh -A'
alias ta='tmux attach'
alias tl='tmux ls'
alias tlmgr='${TEXMFDIST}/scripts/texlive/tlmgr.pl'
alias v='vim'
alias vg='vim +G'
alias vp='vim +PlugUpdate'
alias wlv='cat ~/.lunarvim_in_use_okay_to_delete'
alias wnv='cat ~/.neovim_in_use_okay_to_delete'
alias xz='$EDITOR -c "let g:tty='\''$(tty)'\''"'

# -------------------------------------------------------------------------- }}}
# {{{ Aliases to folders I visit frequently.

alias .a='cd $BASHHOME'
alias .b='cd $BINHOME'
alias .c='cd $CFGHOME'
alias .d='cd $DOTHOME'
alias .g='cd $GITHOME'
alias Cd='cd $GITHOME/color'
alias Dc='cd $HOME/Documents'
alias Dd='cd $HOME/Downloads'
alias Ld='cd $HOME/.local/share/nvim/lsp_servers'
alias ac='cd $GITHOME/AllanConsulting'
alias bd='cd $GITHOME/bootstrap'
alias gd='cd $GITHOME'
alias hh='cd $GITHOME/HowardHouse'
alias ic='cd ~/img-clip'
alias nd='cd $GITHOME/nvim.traap'
alias pd='cd $HOME/.local/share/nvim/site/pack/packer/start'
alias rd='cd $GITHOME/resume'
alias sd='cd $GITHOME/ssh'
alias td='cd $GITHOME/tmux'
alias vb='cd $GITHOME/vim/bundle'
alias vd='cd $GITHOME/vim'
alias wd='cd $WIKIHOME'
alias wk='cd $WORKHOME'
alias yd='cd $YOUTUBEHOME'

alias cal='cd $CFGHOME/alacritty'
alias cbs='cd $CFGHOME/bspwm'
alias cdc='cd $CFGHOME/dconf'
alias cdu='cd $CFGHOME/dunst'
alias cki='cd $CFGHOME/kitty'
alias cnv='cd $CFGHOME/nvim'
alias cpi='cd $CFGHOME/picom'
alias cpo='cd $CFGHOME/polybar'
alias cra='cd $CFGHOME/ranger'
alias csx='cd $CFGHOME/sxhkd'
alias cth='cd $CFGHOME/Thunar'

# -------------------------------------------------------------------------- }}}
# {{{ Brew wants me to own usr/local

if osType "darwin"; then
	alias ulo='sudo chown -R $(whoami) /usr/local'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Repeat command are used when I enable my resume editor.

alias rgl='repeat git logg -6'
alias rgs='repeat git status --short'

# -------------------------------------------------------------------------- }}}
# {{{ Perforce defaults.

if osType "linux"; then
	if hostName "Ryder"; then
		alias p4='${P4DISK}/2013.1/p4'
		alias p4d='${P4DISK}/2013.1/p4d'
	fi
fi

# -------------------------------------------------------------------------- }}}
# {{{ File I edit frequently.  These aliases mirror keybinds used in Vim.
#     TODO: 2023.12.22 Consider pruning this list.

alias ,ec='$EDITOR $GITHOME/ssh/config.vim'
alias ,ed='$EDITOR $GITHOME/vim/custom-dictionary.utf-8.add'
alias ,eg='$EDITOR $GITHOME/ssh/gitconfig'
alias ,en='$EDITOR $GITHOME/nvim.traap/init.lua'
alias ,em='$EDITOR $GITHOME/vim/minimal-plug.vim'
alias ,et='$EDITOR $GITHOME/tmux/tmux.conf'
alias ,ev='$EDITOR $GITHOME/vim/vimrc'

alias ,ma='$EDITOR $BASHHOME/my_aliases'
alias ,mb='$EDITOR $BASHHOME/bashrc'
alias ,mc='$EDITOR $BASHHOME/my_completions'
alias ,me='$EDITOR $BASHHOME/my_exports'
alias ,mf='$EDITOR $BASHHOME/my_functions'
alias ,mp='$EDITOR $BASHHOME/my_paths'
alias ,mt='$EDITOR $BASHHOME/my_prompt'
alias ,mz='$EDITOR $BASHHOME/bashrc-personal'

alias ,xb='$EDITOR $DOTHOME/bspwm/bspwmrc'
alias ,xs='$EDITOR $DOTHOME/sxhkd/sxhkdrc'

# -------------------------------------------------------------------------- }}}
# {{{ tmux sessions I frequently use.

alias tao='ao ao'
alias tbash='ao bash'
alias tkjv='ao kjv'
alias tnvim='ao Nvim'
alias tsoup='ao soup'
alias tvim='ao vim'
alias tspad='ao Scratchpad'
alias td='ao d'
alias th='ao h'
alias tt='ao t'
alias tupd='ao Upgrade'
alias twiki='ao Wiki'
alias tyt='ao YouTube'

alias kao='tmux kill-session -t ao'
alias kbash='tmux kill-session -t bash'
alias kkjv='tmux kill-session -t kjv'
alias knvim='tmux kill-session -t Nvim'
alias kspad='tmux kill-session -t Scratchpad'
alias kd='tmux kill-session -t d'
alias kh='tmux kill-session -t h'
alias kt='tmux kill-session -t t'
alias kupd='tmux kill-session -t Upgrade'
alias kvim='tmux kill-session -t vim'
alias kwiki='tmux kill-session -t Wiki'
alias kyt='tmux kill-session -t YouTube'

# -------------------------------------------------------------------------- }}}
# {{{ archlinux tlmgr (texlive manager)

export TEXMFDIST='/usr/share/texmf-dist'
alias tlmgr='${TEXMFDIST}/scripts/texlive/tlmgr.pl --usermode'

# -------------------------------------------------------------------------- }}}
# {{{ WSL (Windows Subsystem for Linux)

# Windows paths are appended to PATH when WSL is present.

if [[ -n $WSL_DISTRO_NAME ]]; then
	alias wsl=wsl.exe
fi

# -------------------------------------------------------------------------- }}}
# {{{ Neovim appname aliases

if [[   -f "$HOME/.config/nvims/nvim_appnames" ]]; then
	source "$HOME/.config/nvims/nvim_appnames"
fi

# -------------------------------------------------------------------------- }}}
