#!/bin/bash
# {{{ Default Browers, File Manager, and 256 colors.
if [[ -z $WSL_DISTRO_NAME ]]; then
  if programExists brave-browser; then
    export BROWSER=$(which brave-browser)
  elif programExists brave; then
    export BROWSER=$(which brave)
  elif programExists chrome; then
    export BROWSER=$(which chrome)
  elif programExists firefox; then
    export BROWSER=$(which firefox)
  else
    export BROWSER=""
  fi
else
  export BROWSER=brave.exe
fi
export FILE=ranger
export TERM=xterm-256color

# I enable warning when I am debugging .bashrc
echoWarning=0

# -------------------------------------------------------------------------- }}}
# {{{ Darwin CLI and LS colors.

if osType "darwin"; then
  export CLICOLOR=1
  export LSCOLORS=GxFxBxDxCxegedabagacad
fi

# -------------------------------------------------------------------------- }}}
# {{{ amber location.

if dirExists ${GITHOME}/amber; then
   AMBERPATH=${GITHOME}/amber
else
  AMBERPATH=""
  [[ $echoWarning == 1 ]] && echo "WARNING: amber is not installed."
fi
export AMBERPATH

if [[ -d ${AMBERPATH} ]]; then
  newfactoryitem() {
    ${AMBERPATH}/bin/newfactoryitem "$@"
  }
fi

# -------------------------------------------------------------------------- }}}
# {{{ autodoc location.

if  dirExists ${GITHOME}/autodoc; then
  AUTODOCPATH=${GITHOME}/autodoc
else
  [[ $echoWarning == 1 ]] && echo "WARNING: autodoc is not installed."
  AUTODOCPATH=""
fi
export AUTODOCPATH

# -------------------------------------------------------------------------- }}}
# {{{ docbld location and function.  These must go together.

if dirExists ${GITHOME}/docbld; then
  DOCBLDPATH=${GITHOME}/docbld
else
  [[ $echoWarning == 1 ]] && echo "WARNING: docbld is not installed."
  DOCBLDPATH=""
fi
export DOCBLDPATH

# -------------------------------------------------------------------------- }}}
# {{{ dotnet

if dirExists ${HOME}/.dotnet; then
  DOTNET_ROOT=${HOME}/.dotnet
  export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
else
  DOTNET_ROOT=""
fi
export DOTNET_ROOT

# -------------------------------------------------------------------------- }}}
# {{{ emend location.

if dirExists ${GITHOME}/emend; then
   EMENDPATH=${GITHOME}/emend
else
  EMENDPATH=""
  [[ $echoWarning == 1 ]] && echo "WARNING: emend is not installed."
fi
export EMENDPATH

if [[ -d ${EMENDPATH} ]]; then
  newcomponent() {
    ${EMENDPATH}/bin/newcomponent "$@"
  }
fi

# -------------------------------------------------------------------------- }}}
# {{{ Editor.

export MANWIDTH=76
if osType "msys"; then
  EDITOR=$(which vim)
elif programExists nvim; then
  EDITOR=$(which nvim)
elif programExists lvim; then
  EDITOR=$(which lvim)
else
  EDITOR=$(which vim)
fi
export EDITOR

# -------------------------------------------------------------------------- }}}
# {{{ FZF customizations

export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'

# -------------------------------------------------------------------------- }}}
# {{{ HISTCONTROL

export HISTCONTROL=ignoreboth:erasedups

# -------------------------------------------------------------------------- }}}
# {{{ JAVA locations.

if dirExists ${HOME}/build/lclasses/main; then
  CLASSPATH=build/classes/main:build/classes/test
  export CLASSPATH
fi

# -------------------------------------------------------------------------- }}}
# {{{ newdoc location and functions.  These must go together.

if dirExists ${GITHOME}/newdoc; then
   NEWDOCPATH=${GITHOME}/newdoc
else
   [[ $echoWarning == 1 ]] && echo "WARNING: newdoc is not installed."
  NEWDOCPATH=""
fi
export NEWDOCPATH

if [[ -d ${NEWDOCPATH} ]]; then
  newdoc() {
    ${NEWDOCPATH}/newdoc "$@"
  }
fi

# -------------------------------------------------------------------------- }}}
