#!/bin/bash
# I enable warning when I am debugging .bashrc
echoWarning=0

# {{{ Default BROWSER

if [[ -z $WSL_DISTRO_NAME ]]; then
  if "$BINHOME"/programExists brave-browser; then
    BROWSER=$(which brave-browser)
  elif "$BINHOME"/programExists brave; then
    BROWSER=$(which brave)
  elif "$BINHOME"/programExists chrome; then
    BROWSER=$(which chrome)
  elif "$BINHOME"/programExists firefox; then
    BROWSER=$(which firefox)
  else
    BROWSER=""
  fi
else
  BROWSER=brave.exe
  export TEXMFDIST=/usr/share/texlive/texmf-dist
  export TEXMFHOME=/usr/share/texlive/texmf-dist
fi
export BROWSER

# -------------------------------------------------------------------------- }}}
# {{{ TUI file manager

if "$BINHOME"/programExists yazi; then
  FILE=$(which yazi)
fi
  if ! "$BINHOME"/osType "msys"; then
    TERMINAL=""
    [[ $echoWarning == 1 ]] && echo "WARNING: yazi"
  fi
export FILE

# -------------------------------------------------------------------------- }}}
# {{{ TERMINAL

if "$BINHOME"/programExists ghostty; then
  TERMINAL=$(which ghostty)
elif "$BINHOME"/programExists alacritty; then
  TERMINAL=$(which alacritty)
elif "$BINHOME"/programExists kitty; then
  TERMINAL=$(which kitty)
else
  if ! "$BINHOME"/osType "msys"; then
    TERMINAL=""
    [[ $echoWarning == 1 ]] && echo "WARNING: alacritty, ghostty or kitty are not installed."
  fi
fi
export TERMINAL

# -------------------------------------------------------------------------- }}}
# {{{ Darwin CLI and LS colors.

if "$BINHOME"/osType "darwin"; then
  export CLICOLOR=1
  export LSCOLORS=GxFxBxDxCxegedabagacad
fi

# -------------------------------------------------------------------------- }}}
# {{{ amber location.

if "$BINHOME"/dirExists ${SOUPHOME}/amber; then
   AMBERPATH=${SOUPHOME}/amber
else
  AMBERPATH=""
  [[ $echoWarning == 1 ]] && echo "WARNING: amber is not installed."
fi
export AMBERPATH

if [[ -d ${AMBERPATH} ]]; then
  newfactoryitem() {
    ${AMBERPATH}/bin/newfactoryitem "$@"
  }
fi

# -------------------------------------------------------------------------- }}}
# {{{ autodoc location.

if  "$BINHOME"/dirExists ${SOUPHOME}/autodoc; then
  AUTODOCPATH=${SOUPHOME}/autodoc
else
  [[ $echoWarning == 1 ]] && echo "WARNING: autodoc is not installed."
  AUTODOCPATH=""
fi
export AUTODOCPATH

# -------------------------------------------------------------------------- }}}
# {{{ docbld location and function.  These must go together.

if "$BINHOME"/dirExists ${SOUPHOME}/docbld; then
  DOCBLDPATH=${SOUPHOME}/docbld
else
  [[ $echoWarning == 1 ]] && echo "WARNING: docbld is not installed."
  DOCBLDPATH=""
fi
export DOCBLDPATH

# -------------------------------------------------------------------------- }}}
# {{{ dotnet

if "$BINHOME"/dirExists ${HOME}/.dotnet; then
  DOTNET_ROOT=${HOME}/.dotnet
  export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
else
  DOTNET_ROOT=""
fi
export DOTNET_ROOT

# -------------------------------------------------------------------------- }}}
# {{{ emend location.

if "$BINHOME"/dirExists ${SOUPHOME}/emend; then
   EMENDPATH=${SOUPHOME}/emend
else
  EMENDPATH=""
  [[ $echoWarning == 1 ]] && echo "WARNING: emend is not installed."
fi
export EMENDPATH

if [[ -d ${EMENDPATH} ]]; then
  newcomponent() {
    ${EMENDPATH}/bin/newcomponent "$@"
  }
fi

# -------------------------------------------------------------------------- }}}
# {{{ Editor.

export MANWIDTH=76
if "$BINHOME"/programExists nvim; then
  EDITOR=$(which nvim)
elif "$BINHOME"/programExists vim; then
  EDITOR=$(which vim)
else
  EDITOR=""
  [[ $echoWarning == 1 ]] && echo "WARNING: vim or nvim are not installed."
fi
export EDITOR

# -------------------------------------------------------------------------- }}}
# {{{ File manager

if "$BINHOME"/programExists nautilus; then
  FILEMANAGER=$(which nautilus)
elif "$BINHOME"/programExists thunar; then
  FILEMANAGER=$(which thunar)
else
  FILEMANAGER=""
  [[ $echoWarning == 1 ]] && echo "WARNING: Nautlis or Thunar are not installed."
fi
export FILEMANAGER

# -------------------------------------------------------------------------- }}}
# {{{ FZF customizations

export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'

# -------------------------------------------------------------------------- }}}
# {{{ HISTCONTROL

export HISTCONTROL=ignoreboth:erasedups

# -------------------------------------------------------------------------- }}}
# {{{ Ibus settings

#type ibus-setup in terminal to change settings and start the daemon
#delete the hashtags of the next lines and restart
#export GTK_IM_MODULE=ibus
#export XMODIFIERS=@im=dbus
#export QT_IM_MODULE=ibus

# -------------------------------------------------------------------------- }}}
# {{{ JAVA locations.

if "$BINHOME"/dirExists ${HOME}/build/lclasses/main; then
  CLASSPATH=build/classes/main:build/classes/test
  export CLASSPATH
fi

# -------------------------------------------------------------------------- }}}
# {{{ newdoc location and functions.  These must go together.

if "$BINHOME"/dirExists ${SOUPHOME}/newdoc; then
   NEWDOCPATH=${SOUPHOME}/newdoc
else
   [[ $echoWarning == 1 ]] && echo "WARNING: newdoc is not installed."
  NEWDOCPATH=""
fi
export NEWDOCPATH

if [[ -d ${NEWDOCPATH} ]]; then
  newdoc() {
    ${NEWDOCPATH}/newdoc "$@"
  }
fi

# -------------------------------------------------------------------------- }}}
# {{{ Puppeteer

if command -v /usr/bin/chromium >/dev/null 2>&1; then
  export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
else
   [[ $echoWarning == 1 ]] && echo "WARNING: chromium is not installed."
fi
export PUPPETEER_EXECUTABLE_PATH

# -------------------------------------------------------------------------- }}}
