#!/bin/bash
# {{{ Local settings.

wsl_user='garya'

# -------------------------------------------------------------------------- }}}
# {{{ Linux only machines.

# Ruby Environment Manager
if programExists rbenv; then
  eval "$(rbenv init - n)"
fi

# prependToPath only prepends to the path when the directory exists.
prependToPath $HOME/bin
prependToPath $BASHHOME/bin
prependToPath /mnt/c/Users/$wsl_user/AppData/Local/SumatraPDF
prependToPath $HOME/.cargo/bin

# -------------------------------------------------------------------------- }}}
