#!/bin/bash
# {{{ Local settings.

wsl_user='Traap'

# -------------------------------------------------------------------------- }}}
# {{{ Linux only machines.

# Ruby Environment Manager
if programExists rbenv; then
  eval "$(rbenv init - n)"
fi

# prependToPath only prepends to the path when the directory exists.
prependToPath $HOME/bin
prependToPath $BASHHOME/bin
prependToPath $HOME/.cargo/bin

if [[ -n $WSL_DISTRO_NAME ]]; then
  appendToPath /mnt/c/Program\ Files/SumatraPDF
  appendToPath /mnt/c/Users/$wsl_user/AppData/Local/BraveSoftware/Brave-Browser/Application
  appendToPath /mnt/c/Windows/System32
fi

# -------------------------------------------------------------------------- }}}
